name: Tests
on: [push, pull_request]
jobs:
  All-Tests-macOS:
    name: All Tests (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -S . -B ${{github.workspace}}/tmp
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/tmp --target all
          cd ${{github.workspace}}/tmp
          ctest --output-on-failure
